# -*- coding: utf-8 -*-
"""12주차 파이썬 과제

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z1RgoJs19CiB6pFLfI_c8-sfaz1qia2i
"""

#32

set_a = {1, 3, 5, 7, 9}
set_b = {2, 3, 4, 5, 6}

union_set = set_a | set_b
intersection_set = set_a & set_b

print(union_set)
print(intersection_set)

#33

set_c = {10, 20, 30, 40, 50}
set_d = {30, 40, 50, 60, 70}

difference_set = set_c - set_d
symmetric_difference_set = set_c ^ set_d

print(difference_set)
print(symmetric_difference_set)

#34

my_set = {10, 20, 30, 40, 50}
my_set.update([100])

print(my_set)

#35

initial_a = {100, 200, 300, 400, 500}
other_set = {400, 500, 600, 700, 800}

a_intersection = initial_a.copy()
a_intersection.intersection_update(other_set)
print(a_intersection)

a_difference = initial_a.copy()
a_difference.difference_update(other_set)
print(a_difference)

a_symmetric_difference = initial_a.copy()
a_symmetric_difference.symmetric_difference_update(other_set)
print(a_symmetric_difference)

#36

a = {100, 200, 300, 400, 500}
b = {100, 200, 300, 400, 500}

is_superset = a.issuperset(b)
is_subset = a.issubset(b)

if is_superset and is_subset:
    print("동시")
elif is_superset:
    print("상위")
elif is_subset:
    print("부분")

#37

my_set = {1, 10, 20, 30, 40}

my_set.add(1000)
my_set.discard(1000)

print(my_set)

#38

multiples = {x for x in range(1, 101) if x % 3 == 0 and x % 5 == 0}

print(multiples)